
# Packages ----------------------------------------------------------------
library(afex)
library(bayestestR)
library(BayesFactor)
library(bookdown)
library(brms)
library(bpnreg)
library(cowplot)
library(circular)
library(dplyr)
library(emmeans)
library(effects)
library(flextable)
library(flexplot)
library(ggplot2)
library(ggeffects)
library(ggrain)
library(here)
library(ips)
library(irr)
library(janitor)
library(kableExtra)
library(lme4)
library(magick)
library(magrittr)
library(nnet)
library(phia)
library(purrr)
library(psych)
library(rlist)
library(sjPlot)
library(tidybayes)
library(tidyverse)
library(tidyr)
library(viridis)
library(XML)
library(PerformanceAnalytics)
library(effectsize)
library(readxl)
library(openxlsx)
library(Hmisc)


